In [2]:
#1~10까지 2의 간격인 정수값 배열
#.arange(start,stop,step) 사용
import numpy as np
arr=np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [3]:
#모양이 (3,4)인 모든 값이 1인 2차원 배열
#.ones(()) 사용
ones_2d=np.ones((3, 4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#0~1까지 10등분 값 배열
#.linspace(start,stop,num)
arr=np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [5]:
#배열의 속성 출력
import numpy as np
arr1 = np.ones([3,4])
print(arr1)
print('size :', arr1.size)
print('dtype :', arr1.dtype)
print('shape :', arr1.shape)
print('ndim :',arr1.ndim)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size : 12
dtype : float64
shape : (3, 4)
ndim : 2


In [21]:
import numpy as np
A=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25]])
print('Shape :', A.shape)
print(A[3,3])
print(A[:2,:2])
print(A[3:,3:])
print(A[:2,:])
print(A[:,3:])

Shape : (5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [32]:
A=np.arange(1,37,1)
arr_3d=A.reshape(3,3,4)

print(arr_3d)
print('Shape :', arr_3d.shape)
print('Size :', arr_3d.size)

re=arr_3d.reshape(3,4,3)
print(re)

flat=re.flatten()
print(flat)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
Shape : (3, 3, 4)
Size : 36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
